import express from 'express';
import disbursementRollController from '../controllers/disbursementRollController.js';
import { protect } from '../middleware/auth.js';
import { tryCatch } from '../utils/asyncHandler.js';
import { requirePermission } from '../utils/permissions.js';
const router = express.Router();
router.use(protect);
router.get('/', requirePermission('disbursement:view'), tryCatch(disbursementRollController.getMonthlyRoll));
router.patch('/previous', requirePermission('disbursement:modify'), tryCatch(disbursementRollController.updatePreviousDisbursement));
export default router;