import express from 'express';
import predictionController from '../controllers/predictionController.js';
import { protect } from '../middleware/auth.js';
import { requirePermission } from '../utils/permissions.js';
import { tryCatch } from '../utils/asyncHandler.js';
const router = express.Router();
router.use(protect);
router.get('/', requirePermission('prediction:view'), tryCatch(predictionController.getPrediction));
router.post('/', requirePermission('prediction:modify'), tryCatch(predictionController.createOrUpdatePrediction));
export default router;